Empty states
Automattic/simplenote-ios pull request #1031
Opened 2020-11-17 18:51 UTC by eshurakov

### Details
This PR updates Empty States for the following screens:
* All notes
* Tag
* Untagged notes
* Trash
* No Search Results. On this screen added quick action to create a new note with a search term as a title.

Closes #951 

### Test
Check empty state is shown when there are no notes on:
- [ ] All notes
- [ ] Tag
- [ ] Untagged notes
- [ ] Trash
- [ ] Unsuccessful search (from all notes and tag)
- [ ] Tapping on Empty State for unsuccessful search creates a new note with search term as a title

2020-11-18 14:01 UTC, jleandroperez requested changes
Sending you few annoying notes! Looks amazing!!

Please LMK what you think, thank you!

2020-11-18 14:01 UTC, jleandroperez commented on Simplenote/Classes/SPNoteListViewController+Extensions.swift
> +            }
For readability purposes, would it be possible to split this into a smaller method?

Perhaps `var placeholderDisplayMode: DisplayMode` ?

2020-11-18 14:01 UTC, jleandroperez commented on Simplenote/Classes/SPNoteListViewController+Extensions.swift
> +        }
Yet another reason to drop the custom SearchDisplayController!

2020-11-18 14:01 UTC, jleandroperez commented on Simplenote/Classes/SPNoteListViewController+Extensions.swift
> +        open(note, ignoringSearchQuery: true, animated: true)
WDYT if instead of bypassing the search query, we simply exit search mode (and add a new note?)

(Just thinking if we could simplify a bit!)

2020-11-18 14:01 UTC, jleandroperez commented on Simplenote/NoteFactory.swift
> +        let viewContext = SPAppDelegate.shared().managedObjectContext
Idea!!

Rather than querying the NSMOC, how about if we have a property, that must be set in the AppDelegate (before anything else runs)?

Check out [EditorFactory](https://github.com/Automattic/simplenote-ios/blob/develop/Simplenote/Classes/EditorFactory.swift), we do something _slightly_ similar (but not with CoreData precisely)

2020-11-18 14:45 UTC, eshurakov commented on Simplenote/Classes/SPNoteListViewController+Extensions.swift
> +        open(note, ignoringSearchQuery: true, animated: true)
That would be simpler, but not what we want :-) (discussed with Sly)

2020-11-19 11:20 UTC, eshurakov commented on Simplenote/NoteFactory.swift
> +        let viewContext = SPAppDelegate.shared().managedObjectContext
Moved it to `SPObjectManager` 🙈

2020-11-19 11:25 UTC, eshurakov commented on Simplenote/Classes/SPNoteListViewController+Extensions.swift
> +            }
Thank you, done!

2020-11-19 11:25 UTC, eshurakov commented
@jleandroperez, this PR is ready for another look. Thank you!

2020-11-19 12:43 UTC, jleandroperez approved these changes
Awesome work @eshurakov !!!

:shipit:

2020-11-19 13:49 UTC, merged