Fix issue where text could be hidden behind keyboard when sharing to SNshare to simplenote text overflow
Automattic/simplenote-ios pull request #1109
Opened 2021-01-25 08:29 UTC by charliescheer

### Fix
***(Required)*** Add a concise description of what you fixed.  If this is related to an issue, add a link to it.  If applicable, add screenshots, animations, or videos to help illustrate the fix.

### Test
***(Required)*** List the steps to test the behavior.  For example:
> 1. Go to...
> 2. Tap on...
> 3. See error...

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> `RELEASE-NOTES.txt` was updated in d3adb3ef with:
> 
> > Added markdown support

If the changes should not be included in release notes, add a statement to this section. For example:

> These changes do not require release notes.

2021-01-26 13:17 UTC, jleandroperez requested changes
Two notes on this one! The Share Sheet appears to have different behaviors:

- iOS 14 / device: its taking the full available height
- iOS 13 / simulator: Acquires only the available height above the keyboard

In iOS 13 this has a side effect (you end up with extra unneded insets, see video below).

In order to attack this one you may wanna:

A. Switch to `UIKeyboardWillChangeFrameNotification`: because it'll get fired anytime the keyboard's location changes. This happens on iPad when you use the floating keyboard, or Show / Dismiss the keyboard.

B. Adapt the notification handler so that it only applies an Inset for the intersected area.

[Sample code here!](https://github.com/Automattic/simplenote-ios/blob/develop/Simplenote/Classes/SPNoteListViewController+Extensions.swift#L824)

Thank yoou!

https://user-images.githubusercontent.com/1195260/105849494-3ce58880-5fbf-11eb-887b-d78916b9c189.mov

2021-01-27 03:35 UTC, charliescheer commented
Hey @jleandroperez  Questions for you.

>A. Switch to UIKeyboardWillChangeFrameNotification: because it'll get fired anytime the keyboard's location changes. This happens on iPad when you use the floating keyboard, or Show / Dismiss the keyboard.

I am running up against an issue using UIKeyboardWillChangeFrameNotification.  Well two issues, when I started out using keyboard WILL change frame, the value of the size of the keyboard was coming in as where it was, not where it will be.  so the math to change the insets always came out wrong.  If I used keyboard DID change frame then I could get the correct value.  Am I missing something about how to get the correct value from the will change notification?

Second problem, when I am using Did change frame, I am coming up against an issue where after I start interacting with the text view, the notification fires again, but this time the keyboard registers as a different size so it breaks the insets.  It doesn't happen every time, but often enough to be an issue.  I updated the branch to show my latest changes, and here is a quick [video of what is happening](https://d.pr/i/p9hLuT). You can see in the console that initially the calculated value is around 250, which is what we want, but when I click in the text field (sometimes but not all the time) the keyboard frame notification fires again and now I get -8 or sometimes -330




Probably a math error, but I am not sure what is causing it.  Any suggestions?

2021-01-29 13:47 UTC, jleandroperez commented
Hi there @charliescheer!

May I ask you what's the state of this one?

2021-01-31 04:25 UTC, charliescheer commented
Hey @jleandroperez  I put some more work into this today, and something strange is going on.  With the way that this is supposed to be setup/working, the class ExtensionPresentationController should be resizing the ShareViewController textview so that it is just about 8 pts off the keyboard when it appears, and for iPhone it does this correctly, however on iPad (simulator) it does not.

What happens on the iPad is that the sizing calculations end up being about 24 pixels off of where they should be, but what is strange is the values should be correct.  For example on iPhone 12 the screen height is 844, and when the keyboardWillChangeFrame method is called the keyboard height is 336, we are using a padding of 8, so the bottom of the text view should land at 500, and when calculated that is where it lands
but using iPad Air 4, the screen size is 1180, keyboard size is 313 with a padding of 8, so the bottom of the text view should be 836.   When calculated or hard coded that is still too long, and I am not sure why the math works for iPhones (I tried a few others and they seemed to work) but not iPads.

I figure we have two options.  We can continue to look into the why the sizing is not working correctly on iPad (if we go with this one, I would like your help hunting down the issue if possible) OR we could use insets instead of resizing the view.

I personally prefer the second option.  I think that it looks better with the view going longer passed the keyboard and then the edge insets stopping the text from going passed the keyboard instead of there being a little gap and the view being much smaller.  What do you think?

2021-02-09 22:23 UTC, charliescheer commented
closing in favor of #1139

2021-02-09 22:23 UTC, closed without merging