Remove Trailing Comma on Tag
Automattic/simplenote-ios pull request #1138
Opened 2021-02-09 21:19 UTC by illusaen

### Fix
***(Required)*** When entering tags and separating via `, `, tags added had a trailing comma. Removing that comma to be on par with other platforms.

### Test
1. Go to note.
2. Tap on tag field.
3. Enter `tag, `.
4. See that tag is entered as `tag` instead of `tag,`.
5. Check that tags list has tag as `tag`, not `tag,`.

### Screenshots
#### Trailing comma removed:
![tagbug](https://user-images.githubusercontent.com/13263478/107429845-0db83680-6aea-11eb-9bdd-390e929548f2.gif)

#### Mid-word comma still present:
![tagbug-mid](https://user-images.githubusercontent.com/13263478/107429918-258fba80-6aea-11eb-8aba-87b0e83dacd0.gif)

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
`RELEASE-NOTES.txt` was updated in 63c887e5 with: 
`Removing trailing comma from tags when used as delimiter #1120`

2021-02-09 21:22 UTC, dmsnell commented on Simplenote/Classes/SPTagView.m
> +        NSString *cleanedName = [name stringByTrimmingCharactersInSet:[NSCharacterSet punctuationCharacterSet]];
as far as I know this is overly constrictive and will remove tags with legitimate characters. so far we have only disallowed spaces and the comma

2021-02-10 08:21 UTC, eshurakov requested changes
Hi @illusaen, sending you a few comments.

We want to use comma in a similar way that space works now. When you press space or return the tag is created, so pressing comma should do the same.

The best way to achieve this is to update `TagTextFieldInputValidator` and include comma in the character set of disallowed characters. 

Also note that it is also possible to rename a tag from the side bar. The same logic should be applied there as well.

2021-02-10 17:07 UTC, illusaen commented
> Hi @illusaen, sending you a few comments.
> 
> We want to use comma in a similar way that space works now. When you press space or return the tag is created, so pressing comma should do the same.
> 
> The best way to achieve this is to update `TagTextFieldInputValidator` and include comma in the character set of disallowed characters.
> 
> Also note that it is also possible to rename a tag from the side bar. The same logic should be applied there as well.

Hi @eshurakov! Thanks for the tips! I see what you mean, I didn't realize that that was how it should work.

By the way, also replying to @dmsnell in this: I used `punctuationCharacterSet` here because I didn't really think that people would/should? use things like `?/)/etc` in their tags.

2021-02-10 17:49 UTC, illusaen commented
@eshurakov Okay, updated `TagTextFieldInputValidator` and removed the previous change :)

2021-02-11 07:26 UTC, eshurakov reviewed
Thank you!

Do you mind adding a few tests to `TagTextFieldInputValidatorTests`?

Sorry I didn't mention it earlier, but we also need to fix pasting text that contains comma. There is a `preprocessForPasting` method in `TagTextFieldInputValidator`. I think it makes sense to extract disallowed character set to a variable and use it from both `validateInput` and `preprocessForPasting`.

Another note is now that we extended our disallowed set with comma it would make sense to update methods and variables that use `whitespace` in their name to better reflect what's going on. For example we can rename `Result.endingWithWhitespace` to maybe `Result.endingWithDisallowedCharacter`. Suggestions are welcome :-)

2021-02-17 20:41 UTC, illusaen commented
> Thank you!
> 
> Do you mind adding a few tests to `TagTextFieldInputValidatorTests`?
> 
> Sorry I didn't mention it earlier, but we also need to fix pasting text that contains comma. There is a `preprocessForPasting` method in `TagTextFieldInputValidator`. I think it makes sense to extract disallowed character set to a variable and use it from both `validateInput` and `preprocessForPasting`.
> 
> Another note is now that we extended our disallowed set with comma it would make sense to update methods and variables that use `whitespace` in their name to better reflect what's going on. For example we can rename `Result.endingWithWhitespace` to maybe `Result.endingWithDisallowedCharacter`. Suggestions are welcome :-)

Good suggestions all! Done, done, and done :)

2021-02-18 19:34 UTC, eshurakov approved these changes
Works great!

:shipit:

2021-02-18 20:39 UTC, merged

2021-03-09 09:18 UTC, pachlava commented
[testing] fix/feature verified on iPhone XR | iOS 14.4 | Simplenote 4.33.0.0