WIP - Undo via snackbar and copy internal link tests
Automattic/simplenote-ios pull request #1385
Opened 2021-08-06 15:10 UTC by jostnes

### Fix
This is still WIP as the second test case is not working as expected, yet

Adding two new tests to the test suite:
1. Undo trash via snackbar on note list
2. Copy internal link via context menu and pasting to another note

### Test
Test flow:
1. Login > Create 1 note > Trash note > Validate note list is empty > Undo trash > Validate note list not empty
2. Login > Create 1 note > Copy internal link via context menu > Create another note > Paste into new note > Validate internal link of first note pasted

### Review
@pachlava 

### Release
These changes do not require release notes.

2021-08-07 05:38 UTC, jostnes commented on SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
> +            content: "[Copy Internal Link Title-1](simplenote://note/"
a lot of strings here and not sure how to make this one cleaner, they're similar but not entirely the same.

2021-08-07 05:38 UTC, jostnes commented on SimplenoteUITests/UIDs.swift
> +    }
created new enum for context menu, figured it would be better to have it's own instead of storing it with buttons.

2021-08-09 09:06 UTC, pachlava requested changes
Thanks for the other PR @jostnes ! 👍 

I left several notes, I think we can :shipit: after the one related to note input data improvements for `testCopyAndPasteInterlink` and the one related to "steps with no expected results" is adjusted.

2021-08-09 09:06 UTC, pachlava commented on SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
> +        populateNoteList(title: noteName, numberToCreate: 1)
`populateNoteList` is good when we talk about multiple notes creation, but here we need to create only one.

By using `NoteList.createNoteAndLeaveEditor` instead of `populateNoteList` here, you would not need to append "-1" on lines 324 and 331.

2021-08-09 09:06 UTC, pachlava commented on SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
> +        populateNoteList(title: toCopyNoteTitle, numberToCreate: 1)
It's not something official, or accepted as a rule, it's just the way it's done for all existing tests in this project: if the test has a step, the step ends with an assertion. For the sake of consistency, I'd either add an assertion for new note existence to this step, or would merge it with the next step.

Just for some context: as you can see from the [testing checklist](https://github.com/Automattic/simplenote-ios/blob/develop/TESTING-CHECKLIST.md) for Simplenote (it's the only testing document we have for Simplenote), there is no concept of steps, or expected results. A single test is just a single sentence, which is quite vague. 

This current structure for automated tests (multiple steps / expected results) is just a format that I was very used to because of previous experience, and it helped me to logically break down the tests. But it's not official, I'm just proposing you the change because of the consistency.

2021-08-09 09:06 UTC, pachlava commented on SimplenoteUITests/NoteEditor.swift
> +        noteContentTextView.clearAndEnterText(text: enteredValue)
This method does not add a new line after the first characters of note content (instead, you pass a string that already contains the `\n` in the end) so in its current state, it's no different from `NoteEditor.clearAndEnterText`.

In this case, adding this:

```suggestion
        noteContentTextView.clearAndEnterText(text: enteredValue + "\n")
```

Would add meaning to the method, and would also free you from the necessity of having the "\n" in the strings you define in test.

2021-08-09 09:06 UTC, pachlava commented on SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
> +        )
There are several ways to improve this situation a bit:

1. Keeping in mind that you can have a line break automatically added by `NoteEditor.enterTitle`, you no longer need to have "\n" at the end of `toPasteNoteTitle`
2. Since you create only one note via `populateNoteList`, you can use `NoteList.createNoteAndLeaveEditor` instead, and then you have no need to have "-1" in NoteData content.
3. You could adjust the naming a bit, so that the names reflect clearer what are they for.
4. Use [string interpolation](https://www.hackingwithswift.com/read/0/5/string-interpolation), since now you can refer both strings in the note data

In the end, it can look something like this:

```suggestion
        let originalNoteTitle = "Original Note Title"
        let referringNoteTitle = "Referring Note Title"
        let referringNoteData = NoteData(
            name: referringNoteTitle
            content: "[\(originalNoteTitle)](simplenote://note/"
        )
```

2021-08-09 13:07 UTC, jostnes commented on SimplenoteUITests/NoteEditor.swift
> +        noteContentTextView.clearAndEnterText(text: enteredValue)
Good point, totally didn't see this one. I'll update this to include the new line so that it doesn't have to be passed.

2021-08-09 13:07 UTC, jostnes commented on SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
> +        populateNoteList(title: toCopyNoteTitle, numberToCreate: 1)
Yup make sense, would be better for tests to be consistent than having different ways for the same thing which would cause more confusion in the long run. I appreciate comments like this 👍 

In this case would be better to move it to the next step so I'll do that. Also this will be a two "step" test then which I think should be alright so it's:
1. First step - copy and validate
2. Second step - paste and validate

2021-08-09 13:07 UTC, jostnes commented on SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
> +        )
Thanks for the link on string interpolation, I was actually looking for something similar to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) on swift, now I know what it is 😄

2021-08-09 20:27 UTC, pachlava approved these changes

2021-08-09 20:48 UTC, merged