Make method to trigger Buildkite build annotate the caller
Automattic/simplenote-ios pull request #1653
Opened 2024-09-04 06:29 UTC by mokagio

A followup to the work in #1646 #1649 #1650, where to implement any code review feedback or fix for issues discovered found in the process.

_I'll update the title accordingly before merging, for the moment, there is only one meaningful change to report._

### Review
Only one infra engineer required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

2024-09-04 06:29 UTC, dangermattic commented
<!--
  1 Error: PR requires at least one label...
  1 Warning: PR is not assigned to a milest...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-09-04 11:29 UTC, AliSoftware requested changes

2024-09-04 11:29 UTC, AliSoftware commented on fastlane/lanes/release.rb
> +  message = "This build triggered #{build_url} on <code>#{branch}</code>."
`build_url` variable is not defined here. You need to update line 251 to `build_url = buildkite_trigger_build(…)` too for this to be defined 😉

2024-09-06 11:21 UTC, AliSoftware approved these changes

2024-09-09 02:42 UTC, merged