Charlie/textkit 2 round2 mk1
Automattic/simplenote-ios pull request #1690
Opened 2024-12-21 22:56 UTC by charliescheer

### Fix
This PR is the first step in implementing Textkit 2 into Simplenote.  Why do we need this?  Well primarily it is to keep up with the next paradigms in apple development.  Also with the addition of Textkit 2 we should get all of the new Apple intelligence features for free.  Lastly, by removing the reliance on glyphs and glyph ranges in TextKit 2, we should be able to fix many of the out of range crashes that we sometimes see with multi bit character languages.

Here I have taken the first steps.  I have:
- created the TextKit 2 layout properties if the device can run them
- layout the text with the same appearance as text in TextKit 1
- created a graceful fallback to text kit 1

### Test
1.  Launch the app, open a note
- [ ] Confirm that the text is styled correctly for SN
- [ ] Confirm that if you tap into the text you are able to become first responder
- [ ] Confirm that you can enter text
- [ ] Confirm that after you tap into the text you see this warning in the console `UITextView 0x10500fe00 is switching to TextKit 1 compatibility mode because its layoutManager was accessed` but the text is still styled

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer and required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> `RELEASE-NOTES.txt` was updated in d3adb3ef with:
> 
> > Added markdown support

If the changes should not be included in release notes, add a statement to this section. For example:

> These changes do not require release notes.

2024-12-21 22:56 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: View files have been modified,...
  1 Message: This PR is still a Draft: some...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-12-23 15:32 UTC, jleandroperez requested changes
@charliescheer I spotted a couple issues (while running on an iOS 18 device):

### Bug: No Text + Crasher
1. Add a new Note with a single line
2. Go back to the Notes List
3. Open the note again

As a result, the text is not visible. If you attempt to type anything, Simplenote crashes.

https://github.com/user-attachments/assets/07f2bafb-3d16-4ebd-983a-d99922e8ac3e

<img width="300" alt="Screenshot 2024-12-23 at 12 20 51 PM" src="https://github.com/user-attachments/assets/347ad8d9-562b-4fa6-b815-de87bcfdc727" />

### Bug: No Style
1. Add a new Note
2. Write more than one line

As a result, the H1 style is never applied.

https://github.com/user-attachments/assets/d8945ee2-31a6-4965-a892-a8a435706b51

2024-12-23 15:32 UTC, jleandroperez commented on Simplenote/SPFallbackTextContainer.swift
> +            textView.text = newManagerStorage.string
Can we move this so that it's explicit during the initialization flow, rather than a lazy thing?

2024-12-23 15:32 UTC, jleandroperez commented on Simplenote/SPFallbackTextContainer.swift
> +class SPFallbackTextContainer: NSTextContainer {
Annoying comment: Can we add either an `UIKit` import or something, so that the class declaration isn't the very first one in the file?

2024-12-26 20:57 UTC, charliescheer commented
So the problem with the crashing was how the fallback was being setup.  It could mean that there was no text when changes were applied, so the ranges would always be out of bounds.

Discussed in slack and decided instead to approach this in a feature branch rather than building a fallback.  In theory if we are not using TK1 properties then we don't need to fallback.  We don't use them too much already, so if we patch over those for iOS 17 and higher then we should be fine to stay in TK2 always.  Updating the PR to reflect that

2024-12-26 21:04 UTC, charliescheer commented
As for the editing of the header in a new note, this PR is just setting up the TK2 properties and displaying existing notes, it doesn't yet handle editing

2024-12-26 21:36 UTC, jleandroperez commented on Simplenote/SPTextView.swift
> +            layoutManager.addTextContainer(container)
Quick note: `layoutManager` may not be init'ed by the time it's called here

2024-12-26 21:36 UTC, jleandroperez commented on Simplenote/SPTextView.swift
> +        guard let originalText = textContentStorage.textStorage?.attributedSubstring(from: range) as? NSMutableAttributedString else {
Missing `.mutabelCopy()` here

2024-12-26 21:40 UTC, jleandroperez approved these changes
Discussed over Slack, the `mutableCopy()` change is coming up in a follow up.

Please feel free to :shipit: once the `NSLayoutManager` initialization is fixed (fallback flow!).

Nice work @charliescheer !!!

2024-12-26 22:44 UTC, merged