Nü Note Options: Mark IV
Automattic/simplenote-ios pull request #909
Opened 2020-10-09 19:00 UTC by jleandroperez

### Details:
[TBD]

Closes #763

### Test
[TBD]

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> `RELEASE-NOTES.txt` was updated in d3adb3ef with:
> 
> > Added markdown support

2020-10-14 14:25 UTC, aerych requested changes
Hola @jleandroperez 👋 
Code changes look good over all.  I just had two comments (only the first one needs a change):
1. The editor isn't dismissing when trashing.  Looks like we never call `backButtonAction`? Maybe a commit that didn't get pushed?
2. I can dismiss the share sheet by tapping where the screen is greyed out. This trained me to try to do the same with the history slider but I have to tap the Cancel button there.  Would be a nice future enhancement maybe. :) 

Looks good to ship once the editor dismisses! :)

2020-10-14 14:25 UTC, aerych commented on Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
> +            self.delete(note: sender.note)
When trashing a note we want to dismiss the editor, yeah?  Are we missing a call to `self.backButtonAction(sender)` here?

2020-10-15 13:29 UTC, jleandroperez commented
Thank you @aerych!! The `back` invocation was there, at some point, buuut i've been moving code between branches (just trying to find a good balance!), and it got lost along the way.

History Slider is already redone elsewhere (Evgeny's trial project!). 

Thanks a loooot!!

2020-10-15 14:04 UTC, aerych approved these changes

2020-10-15 14:04 UTC, aerych commented
:shipit: sir!!

2020-10-15 14:17 UTC, jleandroperez commented
Thank you Eric!!

2020-10-16 15:29 UTC, merged